# Generated by Django 5.2.7 on 2025-10-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cooperativegroup_flutterwave_subaccount_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paystack_reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
