# Generated by Django 5.2.7 on 2025-11-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loanpayment_manual_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
